# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe('/contact_forms', type: :request) do
     # This should return the minimal set of attributes required to create a valid
     # ContactForm. As you add validations to ContactForm, be sure to
     # adjust the attributes here as well.
     let(:valid_attributes) do
          skip('Add a hash of attributes valid for your model')
     end

     let(:invalid_attributes) do
          skip('Add a hash of attributes invalid for your model')
     end

     before do # Skip authentication for routing
          allow_any_instance_of(Devise::Controllers::Helpers).to(receive(:authenticate_admin!).and_return(true))
     end

     describe 'GET /index' do
          it 'renders a successful response' do
               ContactForm.create!(valid_attributes)
               get contact_forms_url
               expect(response).to(be_successful)
          end
     end

     describe 'GET /show' do
          it 'renders a successful response' do
               contact_form = ContactForm.create!(valid_attributes)
               get contact_form_url(contact_form)
               expect(response).to(be_successful)
          end
     end

     describe 'GET /new' do
          it 'renders a successful response' do
               get new_contact_form_url
               expect(response).to(be_successful)
          end
     end

     describe 'GET /edit' do
          it 'renders a successful response' do
               contact_form = ContactForm.create!(valid_attributes)
               get edit_contact_form_url(contact_form)
               expect(response).to(be_successful)
          end
     end

     describe 'POST /create' do
          context 'with valid parameters' do
               it 'creates a new ContactForm' do
                    expect do
                         post(contact_forms_url, params: { contact_form: valid_attributes })
                    end.to(change(ContactForm, :count).by(1))
               end

               it 'redirects to the created contact_form' do
                    post contact_forms_url, params: { contact_form: valid_attributes }
                    expect(response).to(redirect_to(contact_form_url(ContactForm.last)))
               end
          end

          context 'with invalid parameters' do
               it 'does not create a new ContactForm' do
                    expect do
                         post(contact_forms_url, params: { contact_form: invalid_attributes })
                    end.to(change(ContactForm, :count).by(0))
               end

               it "renders a successful response (i.e. to display the 'new' template)" do
                    post contact_forms_url, params: { contact_form: invalid_attributes }
                    expect(response).to(be_successful)
               end
          end
     end

     describe 'PATCH /update' do
          context 'with valid parameters' do
               let(:new_attributes) do
                    skip('Add a hash of attributes valid for your model')
               end

               it 'updates the requested contact_form' do
                    contact_form = ContactForm.create!(valid_attributes)
                    patch contact_form_url(contact_form), params: { contact_form: new_attributes }
                    contact_form.reload
                    skip('Add assertions for updated state')
               end

               it 'redirects to the contact_form' do
                    contact_form = ContactForm.create!(valid_attributes)
                    patch contact_form_url(contact_form), params: { contact_form: new_attributes }
                    contact_form.reload
                    expect(response).to(redirect_to(contact_form_url(contact_form)))
               end
          end

          context 'with invalid parameters' do
               it "renders a successful response (i.e. to display the 'edit' template)" do
                    contact_form = ContactForm.create!(valid_attributes)
                    patch contact_form_url(contact_form), params: { contact_form: invalid_attributes }
                    expect(response).to(be_successful)
               end
          end
     end

     describe 'DELETE /destroy' do
          it 'destroys the requested contact_form' do
               contact_form = ContactForm.create!(valid_attributes)
               expect do
                    delete(contact_form_url(contact_form))
               end.to(change(ContactForm, :count).by(-1))
          end

          it 'redirects to the contact_forms list' do
               contact_form = ContactForm.create!(valid_attributes)
               delete contact_form_url(contact_form)
               expect(response).to(redirect_to(contact_forms_url))
          end
     end
end
