require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/home_pages", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # HomePage. As you add validations to HomePage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      HomePage.create! valid_attributes
      get home_pages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      home_page = HomePage.create! valid_attributes
      get home_page_url(home_page)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_home_page_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      home_page = HomePage.create! valid_attributes
      get edit_home_page_url(home_page)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new HomePage" do
        expect {
          post home_pages_url, params: { home_page: valid_attributes }
        }.to change(HomePage, :count).by(1)
      end

      it "redirects to the created home_page" do
        post home_pages_url, params: { home_page: valid_attributes }
        expect(response).to redirect_to(home_page_url(HomePage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new HomePage" do
        expect {
          post home_pages_url, params: { home_page: invalid_attributes }
        }.to change(HomePage, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post home_pages_url, params: { home_page: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested home_page" do
        home_page = HomePage.create! valid_attributes
        patch home_page_url(home_page), params: { home_page: new_attributes }
        home_page.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the home_page" do
        home_page = HomePage.create! valid_attributes
        patch home_page_url(home_page), params: { home_page: new_attributes }
        home_page.reload
        expect(response).to redirect_to(home_page_url(home_page))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        home_page = HomePage.create! valid_attributes
        patch home_page_url(home_page), params: { home_page: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested home_page" do
      home_page = HomePage.create! valid_attributes
      expect {
        delete home_page_url(home_page)
      }.to change(HomePage, :count).by(-1)
    end

    it "redirects to the home_pages list" do
      home_page = HomePage.create! valid_attributes
      delete home_page_url(home_page)
      expect(response).to redirect_to(home_pages_url)
    end
  end
end
