require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/positions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Position. As you add validations to Position, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Position.create! valid_attributes
      get positions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      position = Position.create! valid_attributes
      get position_url(position)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_position_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      position = Position.create! valid_attributes
      get edit_position_url(position)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Position" do
        expect {
          post positions_url, params: { position: valid_attributes }
        }.to change(Position, :count).by(1)
      end

      it "redirects to the created position" do
        post positions_url, params: { position: valid_attributes }
        expect(response).to redirect_to(position_url(Position.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Position" do
        expect {
          post positions_url, params: { position: invalid_attributes }
        }.to change(Position, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post positions_url, params: { position: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested position" do
        position = Position.create! valid_attributes
        patch position_url(position), params: { position: new_attributes }
        position.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the position" do
        position = Position.create! valid_attributes
        patch position_url(position), params: { position: new_attributes }
        position.reload
        expect(response).to redirect_to(position_url(position))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        position = Position.create! valid_attributes
        patch position_url(position), params: { position: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested position" do
      position = Position.create! valid_attributes
      expect {
        delete position_url(position)
      }.to change(Position, :count).by(-1)
    end

    it "redirects to the positions list" do
      position = Position.create! valid_attributes
      delete position_url(position)
      expect(response).to redirect_to(positions_url)
    end
  end
end
